### ISSUE TITLE
name of the frame

### ISSUE THREAD

**Issue by kazuho** [quicwg/reliable-stream-reset#19]
As discussed at IETF 117, we can either:
* keep CLOSE_STREAM,
* go back to RELIABLE_RESET_STREAM, or
* something else.

**Comment by kazuho** [comment]
My weak preference goes to retaining CLOSE_STREAM.

Senders can use this frame in place of FIN, with the additional capability of transmitting an error code.

We also know that there were interest in truncating data but not sending an error, it might make sense to point out that the frame can carry a "NO_ERROR" error code.

If we change the name to "RELIABLE_RESET_STREAM," people might have difficulty in understanding that this frame can be used in such ways, not to mention that the internal semantics of the frame is much close to FIN rather than RESET_STREAM (as the new frame cannot be sent until flow control permits doing so).

**Comment by marten-seemann** [comment]
Thank you for weighing in here @nibanks!

@mjoras, CLOSE_STREAM was your suggestion, and to me it made sense when we still had the variant that closed the stream without an error. Now that we removed that variant, would you be opposed to renaming the frame back to RELIABLE_RESET_STREAM?

I'm not sure how to best make progress here, so any suggestions how to quickly reach a name that everyone can live with would be appreciated. Also pinging @LPardue here, since this has the potential to delay publication.

**Comment by marten-seemann** [comment]
Re-reading https://www.ietf.org/archive/id/draft-thomson-quic-enough-00.html, @martinthomson called the frame RESET_AT there. This would be another option (or RESET_STREAM_AT).

It would also exhibit a nice symmetry if we decide to merge this document with ENOUGH, since we could call that frame STOP_SENDING_AT.

**Comment by martinthomson** [comment]
RESET_STREAM_AT/STOP_SENDING_AT sounds cool
