### ISSUE TITLE
Clarify more if it CLOSE_STREAM && RESET_STREAM or CLOSE_STREAM || RESET_STREAM

### ISSUE THREAD

**Issue by LPardue** [quicwg/reliable-stream-reset#20]
Might just be me, but I read

> Conceptually, the CLOSE_STREAM frame is a RESET_STREAM frame with an added Reliable Size field.

And was lead down the false path to think it is a direct substitute for RESET_STREAM. However,

> When resetting a stream, the node has the choice between using a RESET_STREAM frame and a CLOSE_STREAM frame of type 0x21.

the and in this sentence threw me off. 

I'm not  exactly sure what is expected. This seems a problem when a peer sends STOP_SENDING and I might be able to reply with either CLOSE_STREAM or RESET_STREAM because these things behave differently. The the peer really needs one type but the sender decides arbitrarily, bad stuff could happen. 

Depending if it is an && or || relationship, we might really need to pull in something like the [ENOUGH frame](https://www.ietf.org/archive/id/draft-thomson-quic-enough-00.html) to make this stuff really separate and unambiguous.

**Comment by kazuho** [comment]
@LPardue 
>> When resetting a stream, the node has the choice between using a RESET_STREAM frame and a CLOSE_STREAM frame of type 0x21.
> 
> the and in this sentence threw me off.

The sentence is *between 〜 and*, so I think the intent is to state that CLOSE_STREAM frame with Reliable Size of 0 can be sent in place of a RESET_STREAM frame.

That said, I think I agree that we have ambiguity around how endpoints could respond to STOP_SENDING. Are they allowed to respond with a CLOSE_STREAM frame with a non-zero Reliable Size?

I am inclined to say that the answer is no, as that changes the semantics of QUIC v1. If there is interest in having the capability of asking the peer to stop sending after certain offset, then yes we need a new frame for requesting that.

Finally, honestly I think it might be misleading to state that "**conceptually**, the CLOSE_STREAM frame is a RESET_STREAM frame with an added Reliable Size field," with the reason being that the state machinery of a CLOSE_STREAM frame is much closer to a FIN rather than RESET_STREAM.

I think it might be a good idea to change "conceptually" to something like "encoding-wise," or something.

**Comment by LPardue** [comment]
> @LPardue
> 
> > > When resetting a stream, the node has the choice between using a RESET_STREAM frame and a CLOSE_STREAM frame of type 0x21.
> > 
> > 
> > the and in this sentence threw me off.
> 
> The sentence is _between 〜 and_, so I think the intent is to state that CLOSE_STREAM frame with Reliable Size of 0 can be sent in place of a RESET_STREAM frame.

IMHO that's an equality for one manifestation of CLOSE_STREAM. That seems fine and we should probably highlight it.

> 
> That said, I think I agree that we have ambiguity around how endpoints could respond to STOP_SENDING. Are they allowed to respond with a CLOSE_STREAM frame with a non-zero Reliable Size?
> 
> I am inclined to say that the answer is no, as that changes the semantics of QUIC v1. If there is interest in having the capability of asking the peer to stop sending after certain offset, then yes we need a new frame for requesting that.

The RTP over QUIC draft potentially has this problem right now. I think it might be worth serious consideration for including `ENOUGH` (bikeshed on names) in this draft and under a common Transport Param.

> 
> Finally, honestly I think it might be misleading to state that "**conceptually**, the CLOSE_STREAM frame is a RESET_STREAM frame with an added Reliable Size field," with the reason being that the state machinery of a CLOSE_STREAM frame is much closer to a FIN rather than RESET_STREAM.
> 
> I think it might be a good idea to change "conceptually" to something like "encoding-wise," or something.

Yes, no matter the above outcomes, we can tweak this text as an improvement. Lets spin it off to separate issue?
